version: '3.9'
services:

  entry:
    image: nginx:1.23.2
    volumes:
      - ./entry/www:/usr/share/nginx/html:ro
      - ./entry/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./entry/config/cert:/etc/nginx/cert
    ports:
      - "80:80"
      - "443:443"
      - "8099:8099"
    networks:
      - net
    restart: always
    depends_on:
      - server

  website:
    image: nginx:1.23.2
    volumes:
      - ./website/www:/usr/share/nginx/html:ro
      - ./website/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    hostname: website
    networks:
      - net
    restart: always

  admin:
    image: nginx:1.23.2
    volumes:
      - ./admin/www:/usr/share/nginx/html:ro
      - ./admin/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8010:80"
    hostname: admin
    networks:
      - net
    restart: always
    depends_on:
      - server

  graph:
    image: nginx:1.23.2
    volumes:
      - ./graph/www:/usr/share/nginx/html:ro
      - ./graph/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8020:80"
    hostname: graph
    networks:
      - net
    restart: always
    depends_on:
      - server

  medical:
    image: nginx:1.23.2
    volumes:
      - ./medical/www:/usr/share/nginx/html:ro
      - ./medical/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8030:80"
    hostname: medical
    networks:
      - net
    restart: always
    depends_on:
      - server

  server:
    # image: python:3.10.8
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8090:8090"
    hostname: server
    networks:
      - net
    restart: always
    depends_on:
      - mysql
      # - neo4j

  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "Emzujju12!"
      MYSQL_DATABASE: bx_saas
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    hostname: mysql
    networks:
      - net
    privileged: true
    restart: always
    user: root
    command: --default-authentication-plugin=mysql_native_password

  # neo4j:
  #   image: neo4j:5.1.0-community
  #   volumes:
  #     - ./neo4j/data:/data
  #   ports:
  #     - "7474:7474"  # HTTP
  #     - "7687:7687"  # Bolt
  #   hostname: neo4j
  #   networks:
  #     - net
  #   restart: always
  #   user: root

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
