version: '3.8'
services:

  client:
    image: nginx:1.23.2
    volumes:
      - ./client/www:/usr/share/nginx/html:ro
      - ./client/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    networks:
      - net
    restart: always
    depends_on:
      - server

  portal:
    image: nginx:1.23.2
    volumes:
      - ./portal/www:/usr/share/nginx/html:ro
      - ./portal/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8010:80"
    networks:
      - net
    restart: always
    depends_on:
      - server

  server:
    # image: python:3.10.8
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8080:8080"
    hostname: server
    networks:
      - net
    restart: always
    depends_on:
      - mysql
      - neo4j

  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "Emzujju12!"
      MYSQL_DATABASE: bx_saas
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    hostname: mysql
    networks:
      - net
    privileged: true
    restart: always
    user: root
    command: --default-authentication-plugin=mysql_native_password

  neo4j:
    image: neo4j:5.1.0-community
    volumes:
      - ./neo4j/data:/data
    ports:
      - "7477:7474"  # HTTP
      - "7688:7687"  # Bolt
    hostname: neo4j
    networks:
      - net
    restart: always
    user: root

  doc:
    image: nginx:1.23.2
    volumes:
      - ./doc/www:/usr/share/nginx/html:ro
      - ./doc/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8020:80"
    hostname: doc
    networks:
      - net
    restart: always

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
